# Each route describes how an incoming URL is going to be processed by Platform.sh.
"https://www.{default}/":
  type: upstream
  upstream: "sponsorship:http"

"https://{default}/":
  type: redirect
  to: "https://www.{default}/"

  "https://www.{default}/ws":
  type: upstream
  upstream: "sponsorship:http"
  cache:
    enabled: false

